import { readFile } from "node:fs/promises";
import { basename, extname } from "node:path";
import { performance } from "node:perf_hooks";

const ENDPOINT = "https://api.lingolix.com/api/pronunciation/v3/check";

function readArgument(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

const audioPath = readArgument("--audio");
const sentence = readArgument("--sentence");
const languageCode = readArgument("--language") ?? "en";
const apiKey = process.env.LINGOLIX_API_KEY?.trim();

if (!audioPath || !sentence) {
  throw new Error(
    "Usage: node --env-file=.env scripts/lingolix-smoke.mjs --audio <path> --sentence <text> [--language en]",
  );
}
if (!apiKey) throw new Error("LINGOLIX_API_KEY is not configured.");

const mimeTypes = new Map([
  [".wav", "audio/wav"],
  [".webm", "audio/webm"],
  [".ogg", "audio/ogg"],
  [".mp3", "audio/mpeg"],
  [".m4a", "audio/mp4"],
]);
const extension = extname(audioPath).toLowerCase();
const mimeType = mimeTypes.get(extension);
if (!mimeType) throw new Error(`Unsupported smoke-test audio extension: ${extension}`);

const bytes = await readFile(audioPath);
const fileName = basename(audioPath);
const body = new FormData();
body.set("speechdata", new Blob([bytes], { type: mimeType }), fileName);
body.set("sentence", sentence);
body.set("language_code", languageCode);

console.log(JSON.stringify({
  request: {
    method: "POST",
    url: ENDPOINT,
    authorization: "Bearer <redacted>",
    contentType: "multipart/form-data (boundary generated by fetch)",
    fields: {
      speechdata: { fileName, mimeType, sizeBytes: bytes.byteLength },
      sentence,
      language_code: languageCode,
    },
  },
}, null, 2));

const startedAt = performance.now();
const response = await fetch(ENDPOINT, {
  method: "POST",
  headers: { Authorization: `Bearer ${apiKey}` },
  body,
});
const latencyMs = Math.round(performance.now() - startedAt);
const rawBody = await response.text();
let responseBody;
try {
  responseBody = JSON.parse(rawBody);
} catch {
  responseBody = { nonJsonBody: rawBody.slice(0, 2_000) };
}

console.log(JSON.stringify({
  response: {
    status: response.status,
    statusText: response.statusText,
    latencyMs,
    body: responseBody,
  },
}, null, 2));

if (!response.ok) process.exitCode = 1;
