installed_at: '2026-08-08T07:49:43+00:00'
skill_id: git/executing-plans
git_repo: https://github.com/obra/superpowers
skill_path: C:\Users\aloha\AppData\Local\Temp\skilz-git-uby278nu\skills\executing-plans
git_sha: 44c9b2d6e889982ac18c27d05a19fefe335194e1
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
